name: Maven
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'liberica'
      - name: Build with Gradle
        run: ./gradlew clean -x sourcesJar -x JavadocJar -Pgroup=com.github.Olzie-12 -Pversion=30d9c13774l
      - name: Move Jar
        run: mv build/libs/JDA.jar build/jarsjda/
      - name: Deploy to FTP
        uses: Olzie-12/FTP-Deploy-Action@4.3.2
        with:
          local-dir: build/jarsjda/
          server: ${{secrets.FTP_IP_BOTS}}
          server-dir: ${{secrets.FTP_PATH_BOTS}}
          username: ${{secrets.FTP_USERNAME_BOTS}}
          password: ${{secrets.FTP_PASSWORD_BOTS}}
